### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by PeterWillems** [sysunite/coins-2-sdk#1]
_"This version of C:\Local\My Documents\My Projects\TNO\COINS\CLI\coins-cli.exe is
 not compatible with the version of Windows you're running. Check your computer'
s system information to see whether you need a x86 (32-bit) or x64 (64-bit) vers
ion of the program, and then contact the software publisher."_

Any idea how to solve this issue?

**Comment by bastbijl** [comment]
Which version of Windows do you use? There is a prerelease available of a coins-cli.exe version that has less strict dependencies here:

https://github.com/sysunite/coins-2-sdk/tree/validator/dist

This might solve it, but please let us know your findings and the OS you are trying to use this on.

**Comment by bastbijl** [comment]
Update: I'm able to run the coins-cli.exe both on an 64bit Windows 10 and on a 32bit Windows 7. This means that I've not been able to reproduce this behaviour so far.

**Comment by PeterWillems** [comment]
Hi Bastiaan,

See my system description below.

[cid:image001.png@01D20E6B.0D8DEBE0]

Using the link you sent me, returns some information about the problem:

[cid:image002.png@01D20E6B.0D8DEBE0]

The file-not-found exception is strange since I added the IKVM folder to my system path.

Regards,
Peter



Dr. ir. P.H. (Peter) Willems
Research Scientist
Structural Reliability

T +31 (0)88 866 31 39
M +31 (0)61 026 94 70
E peter.willems@tno.nl<mailto:peter.willems@tno.nl>

Location<http://www.tno.nl/locaties/DTM>



[cid:image003.gif@01D20E6B.0D8DEBE0]<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by bastbijl** [comment]
Can you try what happens if you put the ikvm dlls in the same folder?
